2024-10-06 09:05:58,429 ERROR: Exception on /api/attractions/bookings [POST] [in C:\my\ticket-booking\.venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\my\ticket-booking\.venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\my\ticket-booking\.venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\my\ticket-booking\.venv\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\my\ticket-booking\.venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\my\ticket-booking\.venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\my\ticket-booking\backend\api\app.py", line 113, in booking
    if fetched_attraction.get('available_tickets') < sum([ticket.get('quantity') for ticket in tickets.get('tickets')]):
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'sqlite3.Row' object has no attribute 'get'
2024-10-06 09:06:00,100 ERROR: Exception on /api/attractions/bookings [POST] [in C:\my\ticket-booking\.venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\my\ticket-booking\.venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\my\ticket-booking\.venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\my\ticket-booking\.venv\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\my\ticket-booking\.venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\my\ticket-booking\.venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\my\ticket-booking\backend\api\app.py", line 113, in booking
    if fetched_attraction.get('available_tickets') < sum([ticket.get('quantity') for ticket in tickets.get('tickets')]):
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'sqlite3.Row' object has no attribute 'get'
2024-10-06 09:06:01,889 ERROR: Exception on /api/attractions/bookings [POST] [in C:\my\ticket-booking\.venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\my\ticket-booking\.venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\my\ticket-booking\.venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\my\ticket-booking\.venv\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\my\ticket-booking\.venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\my\ticket-booking\.venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\my\ticket-booking\backend\api\app.py", line 113, in booking
    if fetched_attraction.get('available_tickets') < sum([ticket.get('quantity') for ticket in tickets.get('tickets')]):
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'sqlite3.Row' object has no attribute 'get'
2024-10-06 09:06:44,314 ERROR: Exception on /api/attractions/bookings [POST] [in C:\my\ticket-booking\.venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\my\ticket-booking\.venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\my\ticket-booking\.venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\my\ticket-booking\.venv\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\my\ticket-booking\.venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\my\ticket-booking\.venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\my\ticket-booking\backend\api\app.py", line 113, in booking
    if fetched_attraction.get('available_tickets') < sum([ticket.get('quantity') for ticket in tickets.get('tickets')]):
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'sqlite3.Row' object has no attribute 'get'
2024-10-06 09:06:44,833 ERROR: Exception on /api/attractions/bookings [POST] [in C:\my\ticket-booking\.venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\my\ticket-booking\.venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\my\ticket-booking\.venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\my\ticket-booking\.venv\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\my\ticket-booking\.venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\my\ticket-booking\.venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\my\ticket-booking\backend\api\app.py", line 113, in booking
    if fetched_attraction.get('available_tickets') < sum([ticket.get('quantity') for ticket in tickets.get('tickets')]):
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'sqlite3.Row' object has no attribute 'get'
2024-10-06 09:07:26,924 ERROR: Exception on /api/attractions/bookings [POST] [in C:\my\ticket-booking\.venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\my\ticket-booking\.venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\my\ticket-booking\.venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\my\ticket-booking\.venv\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\my\ticket-booking\.venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\my\ticket-booking\.venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\my\ticket-booking\backend\api\app.py", line 113, in booking
    if fetched_attraction.get('available_tickets') < sum([ticket.get('quantity') for ticket in tickets.get('tickets')]):
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'sqlite3.Row' object has no attribute 'get'
